name:                gomoku-haskell
version:             0.1.0.0
github:              "githubuser/gomoku-haskell"
license:             BSD3


extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gomoku-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal

library:
  source-dirs: src

executables:
  gomoku-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gomoku-haskell

tests:
  gomoku-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gomoku-haskell
